Moving ./submodules to ./bits

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,5 +1,5 @@
 #!/bin/bash
-[[ -z "$INFO_LEVEL" ]] && source ./submodules/bootstrap/logging
+[[ -z "$INFO_LEVEL" ]] && source ./bits/bootstrap/logging
 # set -euo pipefail ; IFS=$'\n\t'
 
 #-----------
@@ -27,8 +27,8 @@ LOGLEVEL=${LOGLEVEL-1}
 # Install Script
 #-----------
 
-OWNER=$GIT_OWNER ./submodules/bootstrap/mkdir GIT_LOG_DIR
-OWNER=$GIT_OWNER ./submodules/bootstrap/touch ${GIT_LOG_DIR}/${GIT_REPO_NAME}.log
+OWNER=$GIT_OWNER ./bits/bootstrap/mkdir GIT_LOG_DIR
+OWNER=$GIT_OWNER ./bits/bootstrap/touch ${GIT_LOG_DIR}/${GIT_REPO_NAME}.log
 GIT_OUTPUT=${GIT_LOG_DIR}/${GIT_REPO_NAME}.log
 echo > $GIT_OUTPUT
 
@@ -53,7 +53,7 @@ if [[ "`git config --global user.email`" == "" ]]; then
 fi
 
 if [[ ! -e $GIT_APPS_DIR ]]; then
-  OWNER=$GIT_OWNER ./submodules/bootstrap/mkdir GIT_APPS_DIR
+  OWNER=$GIT_OWNER ./bits/bootstrap/mkdir GIT_APPS_DIR
 fi
 
 # NEW repository, so clone it
@@ -63,22 +63,22 @@ if [[ ! -e ${GIT_REPO_DIR} ]]; then
   if [[ "$GIT_OWNER" == "$USER" ]]; then
     (cd ${GIT_APPS_DIR} && GIT_ERRORS=$(git clone ${GIT_URL} ${GIT_REPO_NAME} > ${GIT_OUTPUT} 2>&1))
 
-    ERROR="Unable to clone1 $GIT_REPO_NAME from $GIT_URL due to ..." ./submodules/bootstrap/failonerrors $? $GIT_OUTPUT
+    ERROR="Unable to clone1 $GIT_REPO_NAME from $GIT_URL due to ..." ./bits/bootstrap/failonerrors $? $GIT_OUTPUT
     [ $? -ne 0 ] && exit 1
     debug_all ${GIT_OUTPUT}
 
     (cd ${GIT_APPS_DIR}/${GIT_REPO_NAME} && git checkout ${GIT_TAG} > ${GIT_OUTPUT} 2>&1)
-    ERROR="Unable to checkout $GIT_TAG from $GIT_REPO_NAME due to ..." ./submodules/bootstrap/failonerrors $? $GIT_OUTPUT
+    ERROR="Unable to checkout $GIT_TAG from $GIT_REPO_NAME due to ..." ./bits/bootstrap/failonerrors $? $GIT_OUTPUT
     [ $? -ne 0 ] && exit 1
     debug_all ${GIT_OUTPUT}
   else
     su $GIT_OWNER -c "(cd ${GIT_APPS_DIR} && git clone ${GIT_URL} ${GIT_REPO_NAME} > ${GIT_OUTPUT} 2>&1)"
-    ERROR="Unable to clone $GIT_REPO_NAME (as $GIT_OWNER) from $GIT_URL due to ..." ./submodules/bootstrap/failonerrors $? $GIT_OUTPUT
+    ERROR="Unable to clone $GIT_REPO_NAME (as $GIT_OWNER) from $GIT_URL due to ..." ./bits/bootstrap/failonerrors $? $GIT_OUTPUT
     [ $? -ne 0 ] && exit 1
     debug_all ${GIT_OUTPUT}
 
     su $GIT_OWNER -c "(cd ${GIT_APPS_DIR}/${GIT_REPO_NAME} && git checkout ${GIT_TAG} > ${GIT_OUTPUT} 2>&1)"
-    ERROR="Unable to checkout $GIT_TAG from $GIT_REPO_NAME due to ..." ./submodules/bootstrap/failonerrors $? $GIT_OUTPUT
+    ERROR="Unable to checkout $GIT_TAG from $GIT_REPO_NAME due to ..." ./bits/bootstrap/failonerrors $? $GIT_OUTPUT
     [ $? -ne 0 ] && exit 1
     debug_all ${GIT_OUTPUT}
   fi
