Enhancing the error logging of git project cloning

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,6 @@
 #!/bin/bash
 [[ -z "$INFO_LEVEL" ]] && source ./submodules/bootstrap/logging
-set -euo pipefail ; IFS=$'\n\t'
+# set -euo pipefail ; IFS=$'\n\t'
 
 #-----------
 # Configurations
@@ -27,14 +27,10 @@ LOGLEVEL=${LOGLEVEL-1}
 # Install Script
 #-----------
 
-if [[ $LOGLEVEL -le $DEBUG_LEVEL ]]; then
-  OWNER=$GIT_OWNER ./submodules/bootstrap/mkdir GIT_LOG_DIR
-  OWNER=$GIT_OWNER ./submodules/bootstrap/touch ${GIT_LOG_DIR}/${GIT_REPO_NAME}.log
-  GIT_OUTPUT=${GIT_LOG_DIR}/${GIT_REPO_NAME}.log
-  echo "" > $GIT_OUTPUT
-else
-  GIT_OUTPUT=/dev/null
-fi
+OWNER=$GIT_OWNER ./submodules/bootstrap/mkdir GIT_LOG_DIR
+OWNER=$GIT_OWNER ./submodules/bootstrap/touch ${GIT_LOG_DIR}/${GIT_REPO_NAME}.log
+GIT_OUTPUT=${GIT_LOG_DIR}/${GIT_REPO_NAME}.log
+echo > $GIT_OUTPUT
 
 if [[ "`which git 2> /dev/null`" == "" ]]; then
   notify "  -- Installing git"
@@ -67,10 +63,24 @@ if [[ ! -e ${GIT_REPO_DIR} ]]; then
   # TODO: Andrew was able to get bash to only run 'su' if the user was difference
   if [[ "$GIT_OWNER" == "$USER" ]]; then
     (cd ${GIT_APPS_DIR} && GIT_ERRORS=$(git clone ${GIT_URL} ${GIT_REPO_NAME} > ${GIT_OUTPUT} 2>&1))
+    ERROR="Unable to clone $GIT_REPO_NAME from $GIT_URL due to ..." ./submodules/bootstrap/failonerrors $? $GIT_OUTPUT
+    [ $? -ne 0 ] && exit 1
     debug_all ${GIT_OUTPUT}
-    (cd ${GIT_APPS_DIR}/${GIT_REPO_NAME} && git checkout ${GIT_TAG} > ${GIT_OUTPUT} 2> /dev/null)
+
+    (cd ${GIT_APPS_DIR}/${GIT_REPO_NAME} && git checkout ${GIT_TAG} > ${GIT_OUTPUT} 2>&1)
+    ERROR="Unable to checkout $GIT_TAG from $GIT_REPO_NAME due to ..." ./submodules/bootstrap/failonerrors $? $GIT_OUTPUT
+    [ $? -ne 0 ] && exit 1
+    debug_all ${GIT_OUTPUT}
   else
-    su $GIT_OWNER -c "(cd ${GIT_APPS_DIR} && git clone ${GIT_URL} ${GIT_REPO_NAME} >> ${GIT_OUTPUT} && cd ${GIT_REPO_NAME} && git checkout ${GIT_TAG} >> ${GIT_OUTPUT})"
+    su $GIT_OWNER -c "(cd ${GIT_APPS_DIR} && git clone ${GIT_URL} ${GIT_REPO_NAME} > ${GIT_OUTPUT} 2>&1)"
+    ERROR="Unable to clone $GIT_REPO_NAME (as $GIT_OWNER) from $GIT_URL due to ..." ./submodules/bootstrap/failonerrors $? $GIT_OUTPUT
+    [ $? -ne 0 ] && exit 1
+    debug_all ${GIT_OUTPUT}
+
+    su $GIT_OWNER -c "(cd ${GIT_APPS_DIR}/${GIT_REPO_NAME} && git checkout ${GIT_TAG} > ${GIT_OUTPUT} 2>&1)"
+    ERROR="Unable to checkout $GIT_TAG from $GIT_REPO_NAME due to ..." ./submodules/bootstrap/failonerrors $? $GIT_OUTPUT
+    [ $? -ne 0 ] && exit 1
+    debug_all ${GIT_OUTPUT}
   fi
   debug_all ${GIT_OUTPUT}
 
@@ -81,7 +91,7 @@ elif [[ "$GIT_MODE" = handsoff ]]; then
 # FORCE an update, this will force Docker to skip the cache (not necessarily a good thing)
 elif [[ "$GIT_MODE" = "force" ]]; then
   notify "  -- Forcing a reset to ${GIT_REPO_DIR} (${GIT_BRANCH})"
-  su $GIT_OWNER -c "(cd ${GIT_REPO_DIR} && git checkout ${GIT_BRANCH} >> ${GIT_OUTPUT} && git fetch >> ${GIT_OUTPUT} && git reset --hard ${GIT_REMOTE}/${GIT_BRANCH} >> ${GIT_OUTPUT} && git checkout ${GIT_TAG} >> ${GIT_OUTPUT})"
+  su $GIT_OWNER -c "(cd ${GIT_REPO_DIR} && git checkout ${GIT_BRANCH} > ${GIT_OUTPUT} && git fetch >> ${GIT_OUTPUT} && git reset --hard ${GIT_REMOTE}/${GIT_BRANCH} >> ${GIT_OUTPUT} && git checkout ${GIT_TAG} >> ${GIT_OUTPUT})"
   debug_all ${GIT_OUTPUT}
 
 # BEST EFFORT to update to the latest of the branch
@@ -90,19 +100,19 @@ elif [[ "$GIT_TAG" == "$GIT_BRANCH" ]]; then
   if [[ "$GIT_MODE" == "local" ]]; then
     notify "  -- Checking out ${GIT_REPO_DIR} (${GIT_BRANCH})"
     if [[ "$GIT_OWNER" == "$USER" ]]; then
-      (cd ${GIT_REPO_DIR} && git checkout ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT} && git pull ${GIT_REMOTE} ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT})
+      (cd ${GIT_REPO_DIR} && git checkout ${GIT_BRANCH} 2> /dev/null > ${GIT_OUTPUT} && git pull ${GIT_REMOTE} ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT})
       debug_all ${GIT_OUTPUT}
     else
-      su $GIT_OWNER -c "(cd ${GIT_REPO_DIR} && git checkout . >> ${GIT_OUTPUT} && git checkout ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT} && git pull ${GIT_REMOTE} ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT})"
+      su $GIT_OWNER -c "(cd ${GIT_REPO_DIR} && git checkout . > ${GIT_OUTPUT} && git checkout ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT} && git pull ${GIT_REMOTE} ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT})"
       debug_all ${GIT_OUTPUT}
     fi
   else
-    notify "  -- Force checking out ${GIT_REPO_DIR} (${GIT_BRANCH})"
+    notify "  -- Force checkout ${GIT_REPO_DIR} (${GIT_BRANCH})"
     if [[ "$GIT_OWNER" == "$USER" ]]; then
-      (cd ${GIT_REPO_DIR} && git checkout . >> ${GIT_OUTPUT} && git checkout ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT} && git pull ${GIT_REMOTE} ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT})
+      (cd ${GIT_REPO_DIR} && git checkout . > ${GIT_OUTPUT} && git checkout ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT} && git pull ${GIT_REMOTE} ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT})
       debug_all ${GIT_OUTPUT}
     else
-      su $GIT_OWNER -c "(cd ${GIT_REPO_DIR} && git checkout . >> ${GIT_OUTPUT} && git checkout ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT} && git pull ${GIT_REMOTE} ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT})"
+      su $GIT_OWNER -c "(cd ${GIT_REPO_DIR} && git checkout . > ${GIT_OUTPUT} && git checkout ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT} && git pull ${GIT_REMOTE} ${GIT_BRANCH} 2> /dev/null >> ${GIT_OUTPUT})"
       debug_all ${GIT_OUTPUT}
     fi
   fi
@@ -113,7 +123,7 @@ elif [[ "`cd ${GIT_REPO_DIR} && git name-rev --tags --name-only $(git rev-parse 
 
 else
   notify "  -- Updating ${GIT_REPO_DIR} (${GIT_TAG})"
-  su $GIT_OWNER -c "(cd ${GIT_REPO_DIR} && git checkout . >> ${GIT_OUTPUT} && git fetch >> ${GIT_OUTPUT} && git checkout ${GIT_TAG} >> ${GIT_OUTPUT})"
+  su $GIT_OWNER -c "(cd ${GIT_REPO_DIR} && git checkout . > ${GIT_OUTPUT} && git fetch >> ${GIT_OUTPUT} && git checkout ${GIT_TAG} >> ${GIT_OUTPUT})"
   debug_all ${GIT_OUTPUT}
 fi
 
