Removed grep error in image helper when docker image does not exist

diff --git a/install b/install
--- a/install
+++ b/install
@@ -65,7 +65,7 @@ if [[ ! -e ${GIT_REPO_DIR} ]]; then
   if [[ "$GIT_OWNER" == "$USER" ]]; then
     (cd ${GIT_APPS_DIR} && GIT_ERRORS=$(git clone ${GIT_URL} ${GIT_REPO_NAME} > ${GIT_OUTPUT} 2>&1))
 
-    ERROR="Unable to clone1 $GIT_REPO_NAME from $GIT_URL due to ..." ./bits/bootstrap/failonerrors $? $GIT_OUTPUT
+    ERROR="Unable to clone $GIT_REPO_NAME from $GIT_URL due to ..." ./bits/bootstrap/failonerrors $? $GIT_OUTPUT
     [ $? -ne 0 ] && exit 1
 
     (cd ${GIT_APPS_DIR}/${GIT_REPO_NAME} && git checkout ${GIT_TAG} > ${GIT_OUTPUT} 2>&1)
